export const CHANGE_BANNER_LIST = 'recommend/CHANGE_BANNER_LIST';

export const CHANGE_RECOMMEND_LIST = 'recommend/RECOMMEND_LIST';

export const CHANGE_GETDATA_LOADING = 'recommend/CHANGE_GETDATA_LOADING';
